name: CI

# on: [push]
on:
  push:
    branches:
      - master
      - feat/19-ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint # will run `yarn test` command


 #   steps:
 #     - uses: actions/checkout@v2
 #     - uses: actions/setup-node@v2
 #       with:
 #         node-version: '15.5.x'
 #     - run: |
 #         yarn
 #         yarn lint
 #     - run: ls -lart node_modules
 #     - run: yarn lint


#    steps:
#      - uses: actions/checkout@v1
#      - name: Install node modules
#        run: yarn
#      - name: Run Linting
#        run: yarn lint
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
